fixed check_idf

diff --git a/debian_zshrc b/debian_zshrc
--- a/debian_zshrc
+++ b/debian_zshrc
@@ -3,12 +3,17 @@ export PATH=$HOME/bin:/usr/local/bin:$PATH
 
 # Path to your oh-my-zsh installation.
 export ZSH=$HOME/.oh-my-zsh
+export ENABLE_APLOS=false
+export PASS_PROJECT=false
+export APLOS_IP=mypc
 
 # virtualenvwrapper
 export WORKON_HOME=$HOME/.virtualenvs
 export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
 export GOPATH=$HOME/.go
 export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
+export DISABLE_SSL_ROUTE=true
+export DISABLE_ELASTIC=true
 
 # Dev vm specific
 if [ $HOST = "tanmay-kakkar" ]; then
@@ -70,7 +75,7 @@ ZSH_THEME="agnoster"
 # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(sudo git virtualenvs python fedora autopep8 pip supervisor zsh-syntax-highlighting zsh-256color alias-tips zsh-completions zsh-syntax-highlighting)
+plugins=(sudo git virtualenvs python fedora autopep8 pip supervisor arcanist zsh-syntax-highlighting zsh-256color alias-tips zsh-completions zsh-syntax-highlighting, zsh-autosuggestions alias-tips vundle yum)
 
 source $ZSH/oh-my-zsh.sh
 workon calm
@@ -112,6 +117,7 @@ alias upload_wfs='find ~/Codebases/calm-workflows/ -name "*.wf"|xargs epdb.py im
 alias vimzshrc='vim ~/.zshrc && source $_'
 alias list_my_branches="git for-each-ref --format=' %(authorname) %09 %(refname)'|grep Tanmay|grep remote"
 alias workoff='deactivate'
+alias get_nutanix_egg='scp root@10.5.216.234:"/root/main/.python/dist/nutanix_python-*.egg" ./'
 
 # Arcanist stuff
 arcpath=$HOME/Codebases/arc
@@ -124,9 +130,9 @@ fi
 autoload -U compinit && compinit
 
 # idf_check
-check_idf(){
-	curl $IDF_URL &> /dev/null && restart_idf_container
-}
+# check_idf(){
+# 	curl $IDF_URL &> /dev/null && restart_idf_container
+# }
 
 # build jove 
 build_jove() {
@@ -510,3 +516,32 @@ vaitarna_status() {
 }
 
 alias vaitarna_reboot='vaitarna_shutdown && vaitarna_boot'
+
+# check idf python code
+python_code="
+from calm.lib.model.store.db_session import create_session
+from calm.scripts.cshell import init_contexts
+from calm.lib.model import Cost
+
+
+init_contexts()
+create_session()
+Cost.query()
+"
+check_idf() {
+    echo "Checking the connection.."
+    timeout 10 python -c $python_code
+    if [ "$?" = "0" ]; then
+        echo "Successful"
+        return 0
+    else
+        echo "Failure"
+        return 1
+    fi
+}
+
+function straceall {
+    to_grep=$(echo $1|sed 's/ /\\\|/g')
+    inargs=$(ps aux|grep $to_grep|awk '{print $2}'|sed ':a;N;$!ba;s/\n/ /g'|sed 's/\([0-9]*\)/-p \1/g')
+    strace $(echo $inargs)
+}
